services:
  postgres:
    image: postgres:16-alpine
    container_name: planet_postgres_infra
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  valkey:
    image: valkey/valkey:alpine3.23
    container_name: planet_valkey_infra
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    container_name: planet_minio_infra
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    restart: unless-stopped

  minio_probe:
    image: curlimages/curl:8.5.0
    container_name: planet_minio_probe_infra
    depends_on:
      - minio
    command: [ "sh", "-c", "sleep infinity" ]
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsS http://minio:9000/minio/health/live >/dev/null || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
    restart: unless-stopped

  api:
    build:
      context: ../services/api
      target: prod
    container_name: planet_api_infra
    environment:
      PORT: 8080

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      VALKEY_ADDR: valkey:6379

      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
    expose:
      - "8080"
    depends_on:
      postgres:
        condition: service_healthy
      valkey:
        condition: service_healthy
      minio_probe:
        condition: service_healthy
    restart: unless-stopped

  web:
    build:
      context: ../apps/web
      target: prod
    container_name: planet_web_build_infra
    environment:
      VITE_API_BASE: /api
    volumes:
      - web_dist:/out
    restart: "no"

  nginx:
    image: nginx:stable-alpine3.23
    container_name: planet_nginx_infra
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    depends_on:
      api:
        condition: service_started
      web:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
  web_dist: